title: Wiki of HouseToken
description: Welcome to wiki of HouseToken

# Articles
collections:
  wps:
    title: NODEHOT
    order: 1
    output: true
  rpcapi:
    title: API Documentation
    order: 2
    output: true
  wallet:
    title: Wallet
    order: 3
    output: true
  programs:
    title: Programs
    order: 4
    output: true

# Jekyll Folders
# source: ./themes/km/
collections_dir: ./collections
layouts_dir: ./themes/km/layout
includes_dir: ./themes/km/layout
sass:
  sass_dir: ./themes/km/css
  style: compressed
permalink: pretty
  # Jekyll Settings
defaults:
  -
    scope:
      path: ''
    values:
      layout: home
